#!/usr/bin/env node
/* Regenerates the two derived files from index.html, which is the single
   source of markup truth:

     markup.reference.html      the head bits + body, for pasting into Webflow
     dist/dt-craft.standalone.js  the same body as a string, plus dt-craft.js

   Run after any change to index.html or dist/dt-craft.js:

     node build.js

   Nothing else is generated — dist/dt-craft.css and dist/dt-craft.js are
   edited directly and shipped as-is.
*/
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');

const index = read('index.html');

/* ---------- 1. the body, minus the local script tag ---------- */
const b0 = index.indexOf('<body>');
const b1 = index.lastIndexOf('</body>');
if (b0 < 0 || b1 < 0) throw new Error('index.html: no <body> to extract');

const body = index
  .slice(b0 + '<body>'.length, b1)
  .replace(/[ \t]*<script src="\.\/dist\/dt-craft\.js" defer><\/script>[ \t]*\r?\n?/, '')
  .trim() + '\n';

/* ---------- 2. the head bits a host page also needs ---------- */
/* everything in <head> except the local stylesheet link, which the host
   pulls from the CDN instead, and the charset, which Webflow already sets */
const head = index
  .slice(index.indexOf('<head>') + '<head>'.length, index.indexOf('</head>'))
  .replace(/[ \t]*<link rel="stylesheet" href="\.\/dist\/dt-craft\.css">[ \t]*\r?\n?/, '')
  .replace(/[ \t]*<meta charset="utf-8">[ \t]*\r?\n?/, '')
  .trim() + '\n';

fs.writeFileSync(path.join(ROOT, 'markup.reference.html'), head + '\n\n' + body, 'utf8');

/* ---------- 3. the standalone bundle ---------- */
const craft = read('dist/dt-craft.js')
  .replace(/^\/\*![\s\S]*?\*\/\r?\n/, '');   // drop its banner; this file has its own

const standalone =
`/*! dt-craft standalone - injects the Vault markup, then runs the craft layer.
 *  For a host page with no markup of its own (a blank Webflow page).
 *  No-ops if #vp already exists, so it is safe to leave in place while
 *  sections are rebuilt natively one at a time.
 *
 *  GENERATED by build.js - do not edit. Edit index.html / dist/dt-craft.js.
 */
(function () {
  var MARKUP = ${JSON.stringify(body)};
  function boot() {
    if (document.getElementById("vp")) return;
    var host = document.createElement("div");
    host.innerHTML = MARKUP;
    while (host.firstChild) document.body.insertBefore(host.firstChild, document.body.firstChild);
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})();

${craft}`;

fs.writeFileSync(path.join(ROOT, 'dist/dt-craft.standalone.js'), standalone, 'utf8');

const kb = n => (n / 1024).toFixed(1) + ' KB';
console.log('markup.reference.html    ' + kb(head.length + body.length + 2));
console.log('dist/dt-craft.standalone.js  ' + kb(standalone.length));
