#!/usr/bin/env node
/* Regenerates every derived file. The hand-edited sources are index.html,
   the five lab pages, dist/dt-craft.{css,js} and dist/dt-lab.{css,js}.

   Generated here:

     markup.reference.html        index.html's head bits + body, for Webflow
     dist/dt-craft.standalone.js  the same body as a string, plus dt-craft.js
     dist/dt-lab-chrome.js        nav + palette + atmosphere + footer
     dist/dt-lab-<page>.js        one per lab page: chrome + that page's body

   Run after any change to index.html, a lab page, or dist/dt-craft.js:

     node build.js
*/
'use strict';
const fs = require('fs');
const path = require('path');

/* The tag the generated bundles point their images at. A Webflow page
   cannot resolve ./img/, so the build rewrites those to the CDN --
   which means BUMPING THIS IS PART OF CUTTING A RELEASE. */
const VERSION = 'v1.10.0';
const CDN = `https://cdn.jsdelivr.net/gh/Alexander-DT/dt-craft@${VERSION}`;

const ROOT = __dirname;
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');

const index = read('index.html');

/* ---------- 1. the body, minus the local script tag ---------- */
const b0 = index.indexOf('<body>');
const b1 = index.lastIndexOf('</body>');
if (b0 < 0 || b1 < 0) throw new Error('index.html: no <body> to extract');

const body = index
  .slice(b0 + '<body>'.length, b1)
  .replace(/[ \t]*<script src="\.\/dist\/dt-craft\.js" defer><\/script>[ \t]*\r?\n?/, '')
  .trim() + '\n';

/* ---------- 2. the head bits a host page also needs ---------- */
/* everything in <head> except the local stylesheet link, which the host
   pulls from the CDN instead, and the charset, which Webflow already sets */
const head = index
  .slice(index.indexOf('<head>') + '<head>'.length, index.indexOf('</head>'))
  .replace(/[ \t]*<link rel="stylesheet" href="\.\/dist\/dt-craft\.css">[ \t]*\r?\n?/, '')
  .replace(/[ \t]*<meta charset="utf-8">[ \t]*\r?\n?/, '')
  .trim() + '\n';

fs.writeFileSync(path.join(ROOT, 'markup.reference.html'), head + '\n\n' + body, 'utf8');

/* ---------- 3. the standalone bundle ---------- */
const craft = read('dist/dt-craft.js')
  .replace(/^\/\*![\s\S]*?\*\/\r?\n/, '');   // drop its banner; this file has its own

const standalone =
`/*! dt-craft standalone - injects the Vault markup, then runs the craft layer.
 *  For a host page with no markup of its own (a blank Webflow page).
 *  No-ops if #vp already exists, so it is safe to leave in place while
 *  sections are rebuilt natively one at a time.
 *
 *  GENERATED by build.js - do not edit. Edit index.html / dist/dt-craft.js.
 */
(function () {
  var MARKUP = ${JSON.stringify(body)};
  function boot() {
    if (document.getElementById("vp")) return;
    var host = document.createElement("div");
    host.innerHTML = MARKUP;
    // a fragment, not a loop: inserting one node at a time before
    // body.firstChild puts the whole block in backwards
    var frag = document.createDocumentFragment();
    while (host.firstChild) frag.appendChild(host.firstChild);
    document.body.insertBefore(frag, document.body.firstChild);
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})();

${craft}`;

fs.writeFileSync(path.join(ROOT, 'dist/dt-craft.standalone.js'), standalone, 'utf8');

/* ---------- 4. the shared chrome, for the component lab pages ----------
   The lab pages carry only their components. Lifting the nav, palette,
   atmosphere and footer straight out of index.html is what stops the
   theme switch, the mega menu and the footer drifting out of step with
   the homepage as it changes. */
const slice = (from, to, label) => {
  const a = index.indexOf(from);
  const b = to === null ? index.length : index.indexOf(to, a);
  if (a < 0 || b < 0) throw new Error('index.html: cannot find ' + label);
  return index.slice(a, b).trim();
};

const chromeHead = slice('<div class="mega-scrim"', '<div id="vp">', 'chrome head');
const chromeFoot = (() => {
  const a = index.indexOf('<footer class="site-foot"');
  const b = index.indexOf('</footer>', a);
  if (a < 0 || b < 0) throw new Error('index.html: cannot find the footer');
  return index.slice(a, b + '</footer>'.length);
})();

const chrome =
`/*! dt-lab chrome - the nav, command palette, atmosphere and footer,
 *  lifted verbatim from index.html so the lab pages cannot drift.
 *
 *  GENERATED by build.js - do not edit. Edit index.html.
 */
window.DTChrome = {
  head: ${JSON.stringify(chromeHead)},
  foot: ${JSON.stringify(chromeFoot)}
};
`;
fs.writeFileSync(path.join(ROOT, 'dist/dt-lab-chrome.js'), chrome, 'utf8');

/* ---------- 5. one markup bundle per lab page ----------
   Same idea as the homepage standalone, split per page so a visitor to
   /media never downloads the other four. Each bundle carries the shared
   chrome as well, so a Webflow lab page is three script tags and no
   elements built by hand.

   Local hrefs (media.html) become hosted routes (/media) on the way in:
   the .html files stay openable straight off disk, and the bundles are
   correct for a real site. */
const LAB = ['media', 'cards', 'testimonials', 'cta', 'team', 'backgrounds', 'scroll'];

const labSizes = LAB.map(slug => {
  const src = read(slug + '.html');
  const s0 = src.indexOf('<body>');
  const s1 = src.lastIndexOf('</body>');
  if (s0 < 0 || s1 < 0) throw new Error(slug + '.html: no <body> to extract');

  let pageBody = src
    .slice(s0 + '<body>'.length, s1)
    .replace(/[ \t]*<script src="\.\/dist\/[^"]+" defer><\/script>[ \t]*\r?\n?/g, '')
    .replace(/<!--(?:(?!-->)[\s\S])*?Order matters(?:(?!-->)[\s\S])*?-->\r?\n?/g, '')
    .trim() + '\n';

  pageBody = pageBody
    .replace(/href="index\.html(#[^"]*)?"/g, (_, hash) => `href="/${hash || ''}"`)
    .replace(new RegExp(`href="(${LAB.join('|')})\\.html"`, 'g'), 'href="/$1"')
    /* ./img/ resolves on disk and on the demo; a Webflow page needs the CDN */
    .replace(/(["'(])\.\/img\//g, `$1${CDN}/img/`);

  const bundle =
`/*! dt-lab ${slug} - the markup for the ${slug} lab page, plus the shared
 *  chrome. Pair with dt-lab.js and dt-craft.js, in that order.
 *
 *  GENERATED by build.js - do not edit. Edit ${slug}.html.
 */
window.DTChrome = {
  head: ${JSON.stringify(chromeHead)},
  foot: ${JSON.stringify(chromeFoot)}
};
window.DTLabPage = ${JSON.stringify(slug)};
(function () {
  if (document.getElementById("vp")) return;   // the page carries its own markup
  var host = document.createElement("div");
  host.innerHTML = ${JSON.stringify(pageBody)};
  var frag = document.createDocumentFragment();
  while (host.firstChild) frag.appendChild(host.firstChild);
  document.body.insertBefore(frag, document.body.firstChild);
})();
`;
  fs.writeFileSync(path.join(ROOT, 'dist/dt-lab-' + slug + '.js'), bundle, 'utf8');
  return [slug, bundle.length];
});

/* ---------- 6. the homepage as a markup-only bundle ----------
   dt-craft.standalone.js carries the markup AND the craft layer, which is
   right for a host page that loads nothing else. It is wrong for a site
   that declares dt-lab.js + dt-craft.js once in its footer, because the
   craft layer would then run twice. This is the same markup with the
   craft layer left out, so the homepage takes the same shape as every
   lab page: one bundle in the head, two shared files in the footer. */
const home =
`/*! dt-home - the Vault homepage markup, without the craft layer.
 *  For a site that already loads dt-lab.js and dt-craft.js. If the host
 *  page loads nothing else, use dt-craft.standalone.js instead - loading
 *  both runs the craft layer twice.
 *
 *  GENERATED by build.js - do not edit. Edit index.html.
 */
(function () {
  if (document.getElementById("vp")) return;
  var host = document.createElement("div");
  host.innerHTML = ${JSON.stringify(body.replace(/(["'(])\.\/img\//g, `$1${CDN}/img/`))};
  var frag = document.createDocumentFragment();
  while (host.firstChild) frag.appendChild(host.firstChild);
  document.body.insertBefore(frag, document.body.firstChild);
})();
`;
fs.writeFileSync(path.join(ROOT, 'dist/dt-home.js'), home, 'utf8');

const kb = n => (n / 1024).toFixed(1) + ' KB';
console.log('markup.reference.html    ' + kb(head.length + body.length + 2));
console.log('dist/dt-craft.standalone.js  ' + kb(standalone.length));
console.log('dist/dt-lab-chrome.js    ' + kb(chrome.length));
labSizes.forEach(([slug, n]) => console.log(('dist/dt-lab-' + slug + '.js').padEnd(25) + kb(n)));
console.log('dist/dt-home.js'.padEnd(25) + kb(home.length));
